on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions: { packages: write }
    steps:
      # preapre
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with: { experimental: true }
      - run: task init
      # test
      - run: task --parallel --output prefixed lint test
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with: { name: playwright-report, path: ./tmp/playwright-report/, retention-days: 30 }
      - uses: codecov/codecov-action@v4.0.1
        if: ${{ always() }}
        with: { token: "${{ secrets.CODECOV_TOKEN }}", file: ./tmp/coverage/profile }
      # build
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/PugKong/sharesecrets
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{steps.meta.outputs.tags}}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
